apiVersion: v1
kind: ConfigMap
metadata:
  name: log-config
  namespace: crt-20521594-dev
data:
  log_config.ini: |
    [loggers]
    keys=root,gunicorn,uvicorn

    [handlers]
    keys=console

    [formatters]
    keys=json

    [logger_root]
    level=INFO
    handlers=console

    [logger_gunicorn]
    level=INFO
    handlers=console
    propagate=0

    [logger_uvicorn]
    level=INFO
    handlers=console
    propagate=0

    [handler_console]
    class=logging.StreamHandler
    formatter=json
    stream=ext://sys.stdout

    [formatter_json]
    class=pythonjsonlogger.jsonlogger.JsonFormatter
    format=%(asctime)s %(name)s %(levelname)s %(message)s
    qualname=JsonFormatter