apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: crunchy-postgres-operator
  namespace: openshift-operators
spec:
  channel: v5
  name: crunchy-postgres-operator
  source: community-operators
  sourceNamespace: openshift-marketplace